language: cpp

dist: xenial

services:
- docker

before_install:
- cd build
- curl -L "https://github.com/Tracktion/pluginval/releases/download/latest_release/pluginval_Linux.zip"
  -o pluginval.zip
- unzip pluginval.zip

script:
- "./travis.sh release Ubuntu18"
- tar czvf ChannelSpanner-Linux.tar.gz ChannelSpanner/*

deploy:
  provider: releases
  api_key:
    secure: "CEe/VYClcBkxn1OWF30N+c2wIUS3Jn+lwyAlkvg6IiyevayIFW8Jup1wOcQAfnR/o4MPjm8icQZvJvXTgfDTe6vl1EpQladMQ9ZlH+sIiK7CN7+fefJwTCsnhTm5eGl5o31YD0Zsmha5mQL+PBJSXF5dkWdWSsv5dy3O0S0kaX8jFAMBM/dbz3Ju4/Z5NkeXH5BlcPCfnNAE6JpWBQjo4avYAkrpwljTjTnnO3KJERWOSdYi7yUWUSolpgEzh7WS/NUxEN4LAZt88hqHvUaNS5aer/tBKeP9CsSk/9BhM6YUmPQ3Xgjk1O87VtuJ6sXtHjFozwZvY6Z3irCl8i07bJ5nGo54npcqGH5ror0jS7X3csEUq14Roz26uEm91k4ozkeimQP/YHhLA3n9k0lFmxYcCdiEwmiV5NIBzR68T0CLSm2IJqcMfZwJXSSuvTJk3HoMJekFTpi6ro4mhsxgMRFfe0WjW3/KBQBgN+qF1EF3rtQerXVSLa2RJEblGR5IS/D+CMR+gxY2zVKbxfM+dgcw9n6Mc4V2DwsnSqF+mnkAScP/By/WQTK7M+sCK6Ya/pnPN/begOkZlOVr/d1W4iVAsd3hoIpAI15ewx+tBwh03bryTcQddZH6kFnBp0SGUbnqQMLr1i0JOr1H3RfvMf/tIhhCoAYT6LlSG0puVMQ="
  file: ChannelSpanner-Linux.tar.gz
  skip_cleanup: true
  draft: true
  overwrite: true
  on:
    repo: cameronleger/channelspanner
    tags: true
