language: cpp

dist: xenial

services:
- docker

before_install:
- cd build
- curl -L "https://github.com/Tracktion/pluginval/releases/download/latest_release/pluginval_Linux.zip"
  -o pluginval.zip
- unzip pluginval.zip

script:
- "./travis.sh release Ubuntu18"
- tar czvf ChannelSpanner-Linux.tar.gz ChannelSpanner/*

deploy:
  provider: releases
  api_key:
    secure: hU89GV0HyjAc3QVWvBbDpaGTG/N/GIO3aU43b18zcvx+Qo8qGVQoKLJr1QLxoMcDU7D6/H9gO5Uc8ItoE4aANMO04qYcc7ED4o7l60JU4LN4iKDpAXccJBcDdQwu3IV8h3w/Qqx+jYoznI4As2kCTw0H1jPyuWRlE/JqqCd96unQ6BdUCLV/hICl1BaAughNdTTmywATptf6w/zKuNnAUi9Y4Njd6n4TwvBF/Cnz6pY7RYBWFVPeCRIPE0tIGTgOZPxOHij0MUc+G6IQxb9K5+UBArTRf7LJ7eM3yTIpDeMwd2r9SH3B5oXWganbs+mQifbdbVnvcu4n+quO7tHXeawb+G0oYG3i21qhyBZVbYRcw8PUgaMqI0L0bj+xQynogI9sgedv3FQwlj6234kChlqJSzOAAlFeMyYEc/YUn3d2Gv6BVjq2Rv0onaG7XQy3tLELDlMKIHyLwa2ktObT5wCGq2m2y5Ezioyu81IZcrQOyjfjfX97i7D22JeEkyKWO4tfX/IQof5Xcfcfos3Xgbu1cu0+7P5DWShXoDWxkg9XlMALCAW71VvI1MgSsQIMc2HSvJUrtbresgn9oIoRiUxzr8JEvoP0Bfzvw09ivCzGMGahVWhRYk6IiUx2ovP+c0DrJN8Ehy0WUU0Szy16ftOzs7sL96qGhjHd6c8SvHg=
  file: build/ChannelSpanner-Linux.tar.gz
  skip_cleanup: true
  draft: true
  overwrite: true
  on:
    repo: cameronleger/channelspanner
    tags: true
